[relaychain]
default_command = "<polkadot-binary>"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  rpc_port = 30100
  ws_port = 30101
  
  [[relaychain.nodes]]
  name = "bob"
  rpc_port = 30200
  ws_port = 30201
  
  [[relaychain.nodes]]
  name = "charlie"
  rpc_port = 30300
  ws_port = 30301

  [[relaychain.nodes]]
  name = "dave"
  rpc_port = 30400
  ws_port = 30401
  
[[parachains]]
id = 1000
chain = "statemine-local"
add_to_genesis = true
cumulus_based = true

  [parachains.collator]
  name = "parachain-A-1000-collator-01"
  command = "<polkadot-chanin-binary>"
  rpc_port = 40000
  ws_port = 40001

